stages:
  - stagingAndroid
  - lint

lint:
  stage: lint
  before_script:
    - bash git clone https://github.com/flutter/flutter.git -b stable
    - bash export PATH="$PATH:`pwd`/flutter/bin"
  script:
    - flutter pub get
    - flutter pub run intl_utils:generate
    - flutter pub run build_runner build --delete-conflicting-outputs
    - flutter format ./lib --set-exit-if-changed
    - flutter analyze
  tags:
    - ventura
build_fad_android:
  image: cirrusci/flutter:3.3.10
  stage: stagingAndroid
  variables:
    SECURE_FILES_DOWNLOAD_PATH: './android'
  script:
    - gem install fastlane
    - export GOOGLE_APPLICATION_CREDENTIALS=$SECURE_FILES_DOWNLOAD_PATH
    - cd android && fastlane build_qa versionName="$CI_COMMIT_TAG" buildNumber="$CI_PIPELINE_IID" groups="nws-tester" releaseNotes="$CI_COMMIT_TAG_MESSAGE"
  tags:
    - ventura
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^release-.*$/ && $CI_COMMIT_TAG != null