stages:
  - lint
  - stagingAndroid

lint:
  stage: lint
  script:
    - flutter pub get
    - flutter pub run intl_utils:generate
    - flutter pub run build_runner build --delete-conflicting-outputs
    - flutter format ./lib --set-exit-if-changed
  tags:
    - ventura

build_fad_android:
  stage: stagingAndroid
  variables:
    SECURE_FILES_DOWNLOAD_PATH: './android'
  script:
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - echo "$SECURE_FILES_DOWNLOAD_PATH"
    - export GOOGLE_APPLICATION_CREDENTIALS=$SECURE_FILES_DOWNLOAD_PATH
    - cd android && fastlane beta versionName:"$CI_COMMIT_TAG" buildNumber:"$CI_PIPELINE_IID" groups:"nws-tester" releaseNotes:"$CI_COMMIT_TAG_MESSAGE"
  tags:
    - ventura