// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmQ7_5lJqbwF0Pgx76XNzR9UWT8wB0iZM',
    appId: '1:160322392119:web:3574fa4eca6f2ed9e16fb2',
    messagingSenderId: '160322392119',
    projectId: 'line8-app',
    authDomain: 'line8-app.firebaseapp.com',
    storageBucket: 'line8-app.appspot.com',
    measurementId: 'G-4LFSYGG6H2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbI8cvId6dMrxP47xqOVzIErvdMNIpdGE',
    appId: '1:160322392119:android:994af2d0e09f84eee16fb2',
    messagingSenderId: '160322392119',
    projectId: 'line8-app',
    storageBucket: 'line8-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSDswpQF6NuYmLf22Lzu26XGnQlQznTpg',
    appId: '1:160322392119:ios:61d991269ca6ed2fe16fb2',
    messagingSenderId: '160322392119',
    projectId: 'line8-app',
    storageBucket: 'line8-app.appspot.com',
    iosClientId: '160322392119-on3s9mevbjbfj82aaiasodc3eb6cv8m9.apps.googleusercontent.com',
    iosBundleId: 'vn.newwave.line8',
  );
}
